const baseballData = {
  selectedTeam: {
    name: null,
    image: null,
  },
  matchId: null,
  teamList: [
    {
      id: null,
      name: null,
      logoUrl: null,
    },
  ],
  playerList: {
    status: 200,
    data: [
      {
        team1: "삼성",
        totalAppearance: "4",
        totalHit: "5",
        totalOut: "3",
        players: [
          {
            name: "트라웃",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
        ],
      },
      {
        team1: "LG",
        totalAppearance: "4",
        totalHit: "5",
        totalOut: "3",
        players: [
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
        ],
      },
    ],
  },
  playGround: {
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 0,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "삼성",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "LG",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "2",
          order: "3",
          history: ["1", "1", "3"],
        },
        {
          name: "이대호",
          plateAppearance: "1",
          hit: "2",
          order: "4",
          history: ["1", "2", "4"],
        },
        {
          name: "이대호",
          plateAppearance: "1",
          hit: "2",
          order: "4",
          history: ["1", "2", "4"],
        },
      ],
    },
    ballCount: {
      strike: 2,
      ball: 3,
      out: 2,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "1",
    },
    display: [
      {
        teamName: "삼성",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "5", "6", "7", "8", "9"],
      },
      {
        teamName: "한화",
        where: "HOME",
        totalScore: "0",
        inningScore: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
      },
    ],
  },
};

export default baseballData;
