const baseballData = {
  selectedTeam: {
    name: null,
    image: null,
  },
  teamList: [
    {
      id: 1,
      name: "LA다저스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 2,
      name: "필라델피아",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 3,
      name: "LA에인절스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 4,
      name: "뉴욕양키스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 5,
      name: "LA다저스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 6,
      name: "필라델피아",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 7,
      name: "LA에인절스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 8,
      name: "뉴욕양키스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 9,
      name: "LA다저스",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
    {
      id: 10,
      name: "필라델피아",
      image: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FsfG5j%2Fbtqyjd8BHCx%2FcKTzWIU3jPjZ0h84IKJjm0%2Fimg.jpg",
    },
  ],
  playerList: {
    status: 200,
    data: [
      {
        team1: "삼성",
        totalAppearance: "4",
        totalHit: "5",
        totalOut: "3",
        players: [
          {
            name: "트라웃",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
        ],
      },
      {
        team1: "LG",
        totalAppearance: "4",
        totalHit: "5",
        totalOut: "3",
        players: [
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "이대호",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
          {
            name: "정근우",
            plateAppearance: "1",
            hit: "2",
            out: "1",
            average: "1.000",
          },
        ],
      },
    ],
  },
};

export default baseballData;
