const demo_data = [
  {
    isHit: true,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "Ed",
          plateAppearance: "0",
          hit: "0",
          order: "2",
          history: [],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 0,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "0",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: true,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "hoi",
          plateAppearance: "0",
          hit: "0",
          order: "0",
          history: [],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 0,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "hoi",
          plateAppearance: "1",
          hit: "1",
          order: "3",
          history: ["2"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 1,
      out: 0,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 1,
      ball: 1,
      out: 0,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "won",
          plateAppearance: "0",
          hit: "0",
          order: "4",
          history: [],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 1,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "won",
          plateAppearance: "1",
          hit: "0",
          order: "4",
          history: ["1"],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 1,
      ball: 0,
      out: 1,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "won",
          plateAppearance: "1",
          hit: "0",
          order: "4",
          history: ["1", "2"],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 1,
      ball: 1,
      out: 1,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "Teak",
          plateAppearance: "0",
          hit: "0",
          order: "5",
          history: [],
        },
        {
          name: "won",
          plateAppearance: "2",
          hit: "0",
          order: "4",
          history: ["1", "2", "4"],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 2,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: true,
    isGetScore: false,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "0",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "Hoo",
          plateAppearance: "0",
          hit: "0",
          order: "6",
          history: [],
        },
        {
          name: "Teak",
          plateAppearance: "1",
          hit: "0",
          order: "5",
          history: ["3"],
        },
        {
          name: "won",
          plateAppearance: "2",
          hit: "0",
          order: "4",
          history: ["1", "2", "4"],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 2,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "1",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: true,
    isGetScore: true,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "1",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "휴지",
          plateAppearance: "0",
          hit: "0",
          order: "7",
          history: [],
        },
        {
          name: "Hoo",
          plateAppearance: "1",
          hit: "1",
          order: "6",
          history: ["3"],
        },
        {
          name: "Teak",
          plateAppearance: "1",
          hit: "0",
          order: "5",
          history: ["3"],
        },
        {
          name: "won",
          plateAppearance: "2",
          hit: "0",
          order: "4",
          history: ["1", "2", "4"],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 2,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "1",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["1", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    changeTeam: true,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",
    defenseTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },
    attackTeam: {
      teamName: "기계군단",
      totalScore: "1",
      location: "HOME",
      pitcher: null,
      batter: [
        {
          name: "휴지",
          plateAppearance: "0",
          hit: "0",
          order: "8",
          history: ["4"],
        },
        {
          name: "Hoo",
          plateAppearance: "1",
          hit: "1",
          order: "6",
          history: ["3"],
        },
        {
          name: "Teak",
          plateAppearance: "1",
          hit: "0",
          order: "5",
          history: ["3"],
        },
        {
          name: "won",
          plateAppearance: "2",
          hit: "0",
          order: "4",
          history: ["1", "2", "4"],
        },
        {
          name: "hoi",
          plateAppearance: "2",
          hit: "1",
          order: "3",
          history: ["2", "1", "4"],
        },
        {
          name: "Ed",
          plateAppearance: "1",
          hit: "1",
          order: "2",
          history: ["3"],
        },
        {
          name: "트라웃",
          plateAppearance: "1",
          hit: "1",
          order: "1",
          history: ["3"],
        },
      ],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 2,
    },
    plates: {
      baseFirst: "1",
      baseSecond: "1",
      baseThird: "1",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["1", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
  {
    isHit: false,
    isGetScore: false,
    changeTeam: true,
    gameOver: true,
    defense: "true",
    status: "200",
    matchInfo: {
      currentInning: 1,
      when: "top",
    },
    userWhere: "HOME",
    defense: "true",

    defenseTeam: {
      teamName: "기계군단",
      totalScore: "1",
      location: "HOME",
      pitcher: {
        name: "최동원",
        count: "0",
      },
      batter: null,
    },

    attackTeam: {
      teamName: "인류",
      totalScore: "0",
      location: "AWAY",
      pitcher: null,
      batter: [{ name: "강백호", plateAppearance: "0", hit: "0", order: "0", history: [] }],
    },
    ballCount: {
      strike: 0,
      ball: 0,
      out: 0,
    },
    plates: {
      baseFirst: "0",
      baseSecond: "0",
      baseThird: "0",
    },
    display: [
      {
        teamName: "인류",
        where: "AWAY",
        totalScore: "0",
        inningScore: ["0", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
      {
        teamName: "기계군단",
        where: "HOME",
        totalScore: "0",
        inningScore: ["1", "0", "0", "0", "0", "0", "0", "0", "0"],
      },
    ],
  },
];

export default demo_data;
